---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flux
  name: flux
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 3031
    targetPort: 3031
  selector:
    app: flux
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: flux
  name: flux
  namespace: prometheus
spec:
  endpoints:
  - interval: 30s
    targetPort: metrics
  jobLabel: flux
  selector:
    matchLabels:
      app: flux
  namespaceSelector:
    matchNames:
      - default

