apiVersion: apps/v1
kind: Deployment
metadata:
  name: static
  namespace: static
spec:
  replicas: 1
  selector:
    matchLabels:
      name: static
  template:
    metadata:
      labels:
        name: static
    spec:
      containers:
      - name: nginx 
        image: stillinbeta/static-files
