---
apiVersion: v1
kind: Service
metadata:
  namespace: puccinia
  name: puccinia-service
spec:
  selector:
    name: puccinia
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30434
      port: 12345
      targetPort: 12345
