apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: httpbin
  namespace: sibcom2
spec:
  rules:
  - host: stillinbeta.com
    http:
      paths:
      - backend:
          serviceName: sibcom2-service
          servicePort: 80
