---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: contour
  name: contour
  namespace: heptio-contour
spec:
  clusterIP: None
  ports:
  - port: 8010
    name: metrics
    protocol: TCP
  selector:
    app: contour
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: kube-prometheus
  name: contour
  namespace: prometheus
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    targetPort: 8010
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    interval: 30s
    path: /stats/prometheus
  selector:
    matchLabels:
      app: contour
    namespaceSelector:
      matchNames:
        - heptio-contour
