---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: contour
  name: contour
  namespace: heptio-contour
spec:
  clusterIP: None
  ports:
  - port: 8002
    name: metrics
  selector:
    app: contour
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: kube-prometheus
  name: contour
  namespace: prometheus
spec:
  endpoints:
  - targetPort: 8002
    interval: 30s
    path: /stats/prometheus
  jobLabel: contour
  selector:
    matchLabels:
      app: contour
  namespaceSelector:
    matchNames:
      - heptio-contour
