---
kind: Service
apiVersion: v1
metadata:
  name: prometheus
  namespace: prometheus
spec:
  selector:
    app: prometheus
    prometheus: k8s
  ports:
  - name: promui
    protocol: TCP
    port: 9090
    targetPort: 9090
