---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sibcom2-web
  namespace: sibcom2
  labels:
    app: sibcom2
  annotations:
    flux.weave.works/automated: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sibcom2
  template:
    metadata:
      namespace: sibcom2
      labels:
        app: sibcom2
    spec:
      containers:
      - name: sibcom2
        image: stillinbeta/sibcom2:1562162392
        ports:
        - containerPort: 8000
        env:
        - name: "REDIS_URL"
          value: "redis://redis.sibcom2.svc.cluster.local:6379"
