---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: updater
  namespace: sibcom2
  annotations:
    flux.weave.works/automated: "true"
spec:
  schedule: "0,15,30,45 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: updater
            image: stillinbeta/sibcom2:1554489926
            command: ["/updater"]
            envFrom:
            - secretRef:
                name: "updater-secret"
            env:
            - name: "REDIS_URL"
              value: "redis://redis.sibcom2.svc.cluster.local:6379"
          restartPolicy: Never
